# Generated by Django 5.2.5 on 2025-08-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion_scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
