# Generated by Django 5.2.5 on 2025-08-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_emotion_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(default='일기 제목 없음', max_length=100),
        ),
    ]
