# Generated by Django 5.2.5 on 2025-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
